### ISSUE TITLE
`Task.using(run_after=..)` fails if value is an instance of `datetime.timedelta`

### ISSUE THREAD

**Issue by davidwtbuxton** [RealOrangeOne/django-tasks#129]
Hi,

- Python 3.12
- django==5.1.4
- django-tasks==0.6.0

DEP-0014 says the `run_after` argument can be an instance of datetime or a timedelta. https://github.com/django/deps/blob/main/accepted/0014-background-workers.rst#deferring-tasks

But passing a timedelta fails with the error `AttributeError: 'datetime.timedelta' object has no attribute 'utcoffset'`.

The current code assumes `run_after` is a datetime.

https://github.com/RealOrangeOne/django-tasks/blob/dd1eb52b07c3af9a8e21f44cd7bb8e0c32e7faa6/django_tasks/backends/base.py#L78

My demo code is a Django view like:

```
import datetime

from django.http.response import HttpResponse
from django_tasks import task

@task
def calc(a, b):
    return a + b

def home(request):
    t = calc.using(run_after=datetime.timedelta(minutes=1)).enqueue(2, 2)

    return HttpResponse(repr(t), content_type="text/plain")
```

And here's the full traceback when a request is made:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tests/demo/demo/views.py", line 19, in home
    t = calc.using(
        ^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django_tasks/task.py", line 116, in using
    return replace(self, **changes)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.runtime/python/lib/python3.12/dataclasses.py", line 1588, in replace
    return obj.__class__(**changes)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django_tasks/task.py", line 84, in __post_init__
    self.get_backend().validate_task(self)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django_tasks/backends/base.py", line 78, in validate_task
    if task.run_after is not None and not timezone.is_aware(task.run_after):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/django/utils/timezone.py", line 221, in is_aware
    return value.utcoffset() is not None
           ^^^^^^^^^^^^^^^
AttributeError: 'datetime.timedelta' object has no attribute 'utcoffset'
```

(This traceback is from code running on Google App Engine standard, but I am pretty sure that isn't a factor in this case.)

This is a cool project.

Thanks,

David

**Comment by RealOrangeOne** [comment]
This functionality was removed in cf41181c978a7b87d8d77683fcd419be79596fc9. 

In short, the issue is that it's not immediately obvious when the `timedelta` is evaluated, and in what timezone. If you need `timedelta` support, it'd be fairly simple to add a small wrapper yourself. I'm not opposed to adding it back, but it needs more thought and design for the side-effects.

As an aside, the DEP should not be considered the canonical reference documentation - take a look at the project's README.
